name: Cypress Tests

on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2
    
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:headless
          browser: chrome

      - name: Post Report
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: cypress/reports/Report
permissions: 
  contents: write